### ISSUE TITLE
How to get the value of an attribute?

### ISSUE THREAD

**Issue by AllenDang** [atroche/myws#308]
I just update this lib to newest of master branch and found out that `Node attribute is changed to HashMap<String, String>`, which makes my code doesn't work anymore.

I searched for 2 hours about `how to get value from HashMap<String, String>` and still cannot find the right way to do it (cannot believe I will search for such novice question one day, and the sad part is I didn't get the answer).

Here is my code.
```rust
    for e in tab.wait_for_elements("#rso>div>div>div>div>a")? {
        let attrs = e.get_attributes()?;
        if let Some(attr_map) = attrs {
            let href = attr_map.get("href").unwrap();  // <-- here is the key
            result.push(href.clone());
        }
    }

```

Compiler tells me that 
```rust
    |
15  |             let href = attr_map.get("href").unwrap();
    |                                 --- ^^^^^^ slice indices are of type `usize` or ranges of `usize`
    |                                 |
    |                                 required by a bound introduced by this call
    |
    = help: the trait `SliceIndex<[std::string::String]>` is not implemented for `&str`
```

I don't really understand why?

Can anyone tell me how to get the value of an attribute?

Many thanks from the bottom of my heart!

**Comment by djfm** [comment]
I use this custom helper function:

```rust
fn get_attr(elt: &headless_chrome::Element, attr: &str) -> String {
    match elt.call_js_fn(&format!("function() {{ return this.getAttribute(\"{}\"); }}", attr), vec![], true).unwrap().value {
        Some(Value::String(s)) => s,
        _ => panic!("Expected string"),
    }
}
```
